ReferenceError: Ci is not defined in removeBlankTab.js since Firefox 52, bug 1203813 - Make nsHelperAppDlg dialog be parented by top-level nsIDOMWindow