TypeError: box is null at preferences/overlay/preferencesOverlay.js line 12, we can't call incontentInit for browser versions that don't implement in-content-option (changeset b7e8947f39a5)